### ISSUE TITLE
محدودیت گرفتن آی پی حداکثر برای پنج سرور

### ISSUE THREAD

**Issue by iamomid1997** [Azumi67/6TO4-PrivateIP#1]
با درود و تبریک سال نو
من ۶ تا سرور خارج دارم و ۱ سرور ایران اختصاصی با پهنای باند دارم ولی با این اسکریپت حداکثر میتونم برا ۵ تا از سرورای خارجم آی پی ۶ پرایوت بسازم.
راه حلی هست که بتونم برا سرورای بیشتر از ۵ تا هم آی پی بسازم؟

**Comment by Azumi67** [comment]
سلام بله باید به صورت دستی اضافه کنید . کانفیگ ها را از داخل etc بگیرید و اضافه کنید . پینگ سرویس و اینها رو مانند من بسازید .

**Comment by iamomid1997** [comment]
> سلام بله باید به صورت دستی اضافه کنید . کانفیگ ها را از داخل etc بگیرید و اضافه کنید . پینگ سرویس و اینها رو مانند من بسازید .

فقط فایل های private_*.sh و ping_*.sh رو باید ادیت کنم؟

**Comment by Azumi67** [comment]
بله و یک سرویس پینگ هم درست کنید .

**Comment by iamomid1997** [comment]
> بله و یک سرویس پینگ هم درست کنید .

سرویس پینگ چطور ایجاد کنم؟
