### ISSUE TITLE
از بین رفتن ارتباط دو سرور بعد از ریستارت

### ISSUE THREAD

**Issue by SasanKHZN** [Azumi67/6TO4-PrivateIP#3]
سلام ip6ip6+ipsec و حتی خود 6to4 چرا بعد از ریستارت اتصال دو سرور قطع می شوددر صورتی که ip a میگیریم کنفیگهای تانل موجود هست

**Comment by Azumi67** [comment]
سلام /این مورد در این اسکریپت موجود نمیباشد. شما باید کرون تب رو تست کنید. ممکنه مشکل شما از کار نکردن اون روش بین سرور ایران و خارج شما باشد که یا باید روش را عوض کنید یا سرور خارج را

**Comment by SasanKHZN** [comment]
ممنون از پاسخت من این مورد اشتباه اینجا زدم مربوط به اون یکی اسکریپت هستش ولی ipip6+ipsec که ست میکنیم پینگ ip6 لوکال وجود دارد بعد از ریبوت دو سرور دیگر پینگ ای پی لوکال را ندارند تا سرورا ریست نشه مشکلی وجود ندارد اینترفیس ها سرجاشه وضعیت تانل هم اکی هست فقط پینگ ای پی لوکال را دیگه نداریم

**Comment by Azumi67** [comment]
تست میکنم . دقیقا بگید کدوم گزینه رو زدید .تک سرور یا مولتی .

**Comment by SasanKHZN** [comment]
تک سرور

**Comment by Azumi67** [comment]
بوشه .من کمی بازی کنم تست میکنم .

**Comment by Azumi67** [comment]
خوب من بررسی کردم و یک آپدیت دادم و بعد از ریبوت هم مشکلی نداشتم . شما هم بررسی کنید .

**Comment by SasanKHZN** [comment]
ممنون از لطفت منم اتفاقا وی پی ان و برای بازی استفاده میکنم فقط یک نکته مشکل کجای اسکریپت بوده

**Comment by Azumi67** [comment]
من روت رو تغییر دادم
